# Python Reference-Guide - Numpy

### import Numpy

In [1]:
import numpy as np

### Create a length-10 integer array filled with zeros

In [2]:
a = np.zeros(10, dtype = int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Create a 3x5 floating-point array filled with 1s

In [3]:
a = np.ones((3,5), dtype = float)
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Create a 3x5 array filled with 3.14

In [4]:
a = np.full((3,5), 3.14)
a

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

### Create an array filled with a linear sequence. Starting at 0, ending at 20, stepping by 2 (this is similar to the built-in range() function)

In [5]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Create an array of five values evenly spaced between 0 and 1

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Create a 3x3 array of uniformly distributed random values between 0 and 1

In [7]:
a = np.random.random((3, 3))
a

array([[0.38302055, 0.92342162, 0.12613488],
       [0.50668086, 0.29014905, 0.5366269 ],
       [0.41176191, 0.4032793 , 0.65118757]])

### Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1

In [8]:
a = np.random.normal(0, 1, (3, 3))
a

array([[-0.3087168 ,  0.57832999, -1.29238488],
       [ 2.4465624 ,  0.04838346, -1.1791053 ],
       [ 0.26958179,  1.35539254, -0.13176412]])

### Create a 3x3 identity matrix

In [9]:
np.empty(3)

array([4.94065646e-324, 1.38501006e+219, 3.63071632e+228])